export const brandOneLightColors = {
  brandTop: {
    bg: "#5A2C7C",
    text: "#FFFFFF",
    icon: "#00FF00",
    iconHover: "#FFFFFF", 
  },
   headerUpper: {
    bg: "#FFFFFF",
    text: "#000000",
    textHover: "#5A2C7C",
    searchBg: "#E6DAF0",
    searchHoverBg: "#5A2C7C",
    searchIcon: "#000000",
    searchIconHover: "#FFFFFF",
  },
  mobileMenu: {
    bg: "#FFFFFF",
    text: "#000000",
    textHover: "#5A2C7C",
    overlayBg: "rgba(0,0,0,0.7)",
    closeHoverBg: "#F3F3F3",
  },
 searchOverlay: {
    bg: "#FFFFFF", 
    text: "#000000",
    icon: "#000000", 
    iconHover: "#5A2C7C", 
    border: "#B0B0B0", 
    errorBg: "#FFFFFF", 
    errorBorder: "#000000", 
    errorText: "#000000", 
    errorIconBg: "#FF5A00", 
  },
  banner: {
    bg: "#FFFFFF",
    indicatorActive: "#000000", 
    indicatorInactive: "#CCCCCC", 
  },
 aboutSection: {
  bg: "#FFFFFF",     
  text: "#000000",       
  heading: "#000000",    
  buttonBg: "#5A2C7C",   
  buttonText: "#FFFFFF", 
  buttonHoverBg: "#FFC33C", 
  buttonHoverText: "#000000", 
},
chairmanSection: {
  bg: "#F8F6FF",        
  text: "#2D1B4E",      
  heading: "#1A0C33",   
  buttonBg: "#5A2C7C",   
  buttonText: "#FFFFFF",
  buttonHoverBg: "#00330C", 
  buttonHoverText: "#FFFFFF",
},

achievementsSection: {
    bg: "#E6DAF0",         
    heading: "#00330C",     
    buttonBg: "#5A2C7C",  
    buttonText: "#FFFFFF",
    buttonHoverBg: "#0c0a0aff",
    buttonHoverText: "#FFFFFF",
  },

  managingDirectorSection: {
  bg: "#F9FAFC",        
  text: "#1F2937",       
  heading: "#5A2C7C",    
},

noticeBoardSection: {
  bg: "#F8F6FF",
  heading: "#5A2C7C",
  tableHeaderBg: "#5A2C7C",
  tableHeaderText: "#FFFFFF",
  tableRowBg: "#FFFFFF",
  tableRowAltBg: "#F3F3F3",
  tableBorder: "#0e0713ff", 
  buttonBg: "#5A2C7C",
  buttonText: "#FFFFFF",
  buttonHoverBg: "#00330C",
  buttonHoverText: "#FFFFFF",
},


messageFromMadam: {
  bg: "#FFF9F5",
  heading: "#5A2C7C",
  text: "#333333",
  buttonBg: "#5A2C7C",
  buttonText: "#FFFFFF",
  buttonHoverBg: "#00330C",
  buttonHoverText: "#FFFFFF",
},

footerSection: {
  bgTop: "#1E1E2E",
  bgBottom: "#151521",
  heading: "#FFFFFF",
  text: "#D1D1D1",
  link: "#FFFFFF",
  linkHover: "#9F7AEA",
  iconBg: "#2A2A3D",
  iconHoverBg: "#6B46C1",
  divider: "#3A3A4F",
},

};
